# Generated by Django 3.0.8 on 2020-08-01 17:44

import UserCenter.models.UserImage
import UserCenter.models.UserModel
import UserCenter.models.UserStickers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QiaoQianAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('album_size', models.PositiveSmallIntegerField()),
                ('cover_url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'qiaoqian_album',
            },
        ),
        migrations.CreateModel(
            name='QiaoQianUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_avatar', models.ImageField(upload_to=UserCenter.models.UserModel.avatar_upload_path)),
                ('user_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'qiaoqian_user',
            },
        ),
        migrations.CreateModel(
            name='QiaoQianStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_name', models.CharField(max_length=300)),
                ('sticker_size', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('sticker_img', models.ImageField(upload_to=UserCenter.models.UserStickers.sticker_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserCenter.QiaoQianUser')),
            ],
            options={
                'db_table': 'qiaoqian_sticker',
            },
        ),
        migrations.CreateModel(
            name='QiaoQianImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=300)),
                ('image_size', models.IntegerField()),
                ('image_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=UserCenter.models.UserImage.image_upload_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserCenter.QiaoQianAlbum')),
            ],
            options={
                'db_table': 'qiaoqian_images',
            },
        ),
        migrations.AddField(
            model_name='qiaoqianalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserCenter.QiaoQianUser'),
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('cover_url', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserCenter.QiaoQianUser')),
            ],
            options={
                'db_table': 'qiaoqian_persontype',
            },
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.CharField(max_length=300)),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserCenter.PersonType')),
            ],
            options={
                'db_table': 'qiaoqian_personimage',
            },
        ),
    ]
